
language: python
dist: bionic
cache: pip
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: "78.0.1"
sudo: required
services:
  - xvfb
before_install:
  - nvm use 12.13.1
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver

install: 
  - "pip install -r requirements.txt"
  - npm install selenium-webdriver@^3.0.0
  - node --version
  - npm install
  - npm run build
  - jupyter labextension install .

script: 
  - jupyter labextension list
  - jupyter lab --port=8889 --NotebookApp.token='' &
  - pytest
  
